package dishes;

public enum DinnerDishes{
    CORONATION_CHICKEN, ETON_MESS, SALMON_AND_CUCUMBER_SANDWICHES,
    COLD_ROAST_BEEF_AND_HORSERADISH_ROLLS, STRAWBERRIES_AND_CREAM,
    YORKSHIRE_PUDDING, PIGS_IN_BLANKETS;
}
